### ISSUE TITLE
filtering.md link is not formatted

### ISSUE THREAD

**Issue by nh13** [varlociraptor/varlociraptor.github.io#3]
See `[Filtering]({{< ref "filtering.md" >}})` below:

<img width="778" alt="Screen Shot 2021-04-15 at 4 56 08 PM" src="https://user-images.githubusercontent.com/846274/114952664-949bcf00-9e0b-11eb-9e3b-c097a671a27d.png">

See link: https://varlociraptor.github.io/docs/calling/

**Comment by johanneskoester** [comment]
Solved since a while.

**Comment by johanneskoester** [comment]
Thanks for reporting!
